### ISSUE TITLE
Error message on pupet 3.7.2

### ISSUE THREAD

**Issue by faxm0dem** [logicminds/bmclib#23]
For the following manifest:

```Puppet
class { 'bmclib':}

bmc { 'ipmidevice':
  ensure => present,
  provider => 'ipmitool',
}
```

I'm getting the following error message:

    Error: Could not prefetch bmc provider 'ipmitool': undefined method `find' for #<Puppet::Type::Bmc::ProviderIpmitool:0x7facad506750>

This is on EL6 using puppet 3.7

**Comment by logicminds** [comment]
Thanks for reporting. I assume you do have an ipmi device on that system.  At any rate the error message should be better.

**Comment by faxm0dem** [comment]
I implemented some freeipmi code ([provider and facts](/ccin2p3/bmclib/tree/f/freeipmi)) and dropped this prefetch code because of this.

What does it do?

**Comment by logicminds** [comment]
yea, I see the erorr with prefetch and bad data coming through.  Easy fix.  Can you send a PR for your provider and facts.  That would be awesome to add.

**Comment by faxm0dem** [comment]
Sure thing but before merging it would benefit from some code deduplication

**Comment by logicminds** [comment]
fixed in master branch
